select 'ALTER USER "'||username||'" ACCOUNT UNLOCK'
from DBA_USERS
Where account_status like '%LOCK%' and username not in
('OUTLN', 'DIP', 'ORACLE_OCM', 'APPQOSSYS', 'WMSYS', 'XS$NULL', 'EXFSYS', 'CTXSYS', 'XDB', 'ANONYMOUS', 
 'ORDSYS', 'ORDDATA', 'ORDPLUGINS', 'SI_INFORMTN_SCHEMA', 'MDSYS', 'OLAPSYS', 'MDDATA', 'SPATIAL_WFS_ADMIN_USR', 
 'SPATIAL_CSW_ADMIN_USR', 'FLOWS_FILES', 'APEX_PUBLIC_USER', 'APEX_030200', 'OWBSYS', 'OWBSYS_AUDIT', 'SCOTT', 'SYSMAN')